### ISSUE TITLE
CCC uptime / availability story (use of shared cache)

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-applications#69]

**Comment by dionjwa** [comment]
This ticket is for CCC to use a shared cache, resulting in MDT applications able to use the existing CCC stacks, and making the CCC stacks more reliable and flexible.

**Comment by PeterRJones** [comment]
Yep makes sense Dion. This is your task to have ccc connect to an existing redis cluster.

**Comment by dionjwa** [comment]
This task refers to two CCC features:

Shared redis cache (finished on a dev branch):
https://github.com/Autodesk/cloud-compute-cannon/issues/118

External scaling control:
https://github.com/Autodesk/cloud-compute-cannon/issues/117

@florencio-mazzoldi This ticket will take longer than my original estimate, due to my incorrect assumptions about how easy AWS scaling groups are. I need to investigate whether AWS lambda functions or AWS scaling groups are the best way forward. 

The first part is done, and testing using locally with a docker simulated "cloud", however, it cannot be properly testing in AWS without Autodesk/molecular-design-applications#117 

Estimate of ETA of the second part: midway through this spring (March 1)

**Comment by dionjwa** [comment]
Update: both features are deployed to dev, and all tests are passing. 

External scaling control still needs a few days work.
